"""
Replicate Figure 3 from Roy 2023 (PMID 38125882).

Figure 3 shows horizontal bar charts of VP population distributions for
EPO, Hb, Reticulocytes, and RBC across CKD stages (Healthy, CKD 1.5, 3, 4, 5).
Red dots mark the reference VP values.

This script:
  1. Loads digitized reference VP values from CSV (Rule 2).
  2. Runs the model for each CKD stage to steady state.
  3. Compares model output vs. reference VP values.
  4. Writes a dated JSON artifact (Rule 5).
  5. Produces a comparison figure.

Usage:
    python replicate_fig3.py [--model-dir PATH_TO_MODEL]

Rule compliance:
  - All reference data from: M025_PMID38125882_fig3.csv (no approximations).
  - Artifact written to: evidence/M025_fig3_YYYYMMDD_HHMMSS.json
  - Digitization: Panel C (Retics) flagged UNCERTAIN — excluded from RMSE.
"""
import os
import sys
import json
import csv
import argparse
import datetime
import subprocess

import numpy as np

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _THIS_DIR)

from model import (
    make_params, create_ckd_vp, healthy_ss, ckd_ss,
    get_hgb, get_epo, get_retics, get_rbc,
)

# Evidence and data directories
EVIDENCE_DIR = os.path.join(_THIS_DIR, "evidence")
DATA_DIR     = os.path.join(_THIS_DIR, "data")
os.makedirs(EVIDENCE_DIR, exist_ok=True)

# Reference CSV file (generated by digitize_fig3.py)
CSV_PATH = os.path.join(DATA_DIR, "M025_PMID38125882_fig3.csv")

# ---------------------------------------------------------------------------
# Load reference VP values from digitized CSV
# ---------------------------------------------------------------------------
def load_ref_csv(csv_path):
    """Load CSV into dict: ref[variable][stage] = value."""
    ref = {}
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Digitized CSV not found: {csv_path}")
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            var   = row["series"]
            stage = row["x"]
            val   = float(row["y"])
            if var not in ref:
                ref[var] = {}
            ref[var][stage] = val
    return ref


# ---------------------------------------------------------------------------
# Run model for each CKD stage
# ---------------------------------------------------------------------------
def run_all_stages(spinup_h=30_000):
    """Return dict: model_out[stage] = {EPO, Hb, Retics, RBC}."""
    stages = ["Healthy", "CKD1.5", "CKD3", "CKD4", "CKD5"]
    results = {}
    for stage in stages:
        print(f"  Spinning up {stage} ...", end=" ", flush=True)
        if stage == "Healthy":
            y_ss, p = healthy_ss(), make_params()
        else:
            y_ss, p = ckd_ss(stage, t_spinup=spinup_h)

        hgb    = get_hgb(y_ss, p)
        epo    = get_epo(y_ss)
        retics = get_retics(y_ss)
        rbc    = get_rbc(y_ss)

        results[stage] = {
            "EPO":    epo,
            "Hb":     hgb,
            "Retics": retics,
            "RBC":    rbc,
        }
        print(f"EPO={epo:.2f} Hb={hgb:.2f} Retics={retics:.4f} RBC={rbc:.3f}")

    return results


# ---------------------------------------------------------------------------
# Comparison: compute RMSE per variable (exclude Retics — digitization uncertain)
# ---------------------------------------------------------------------------
def compare(ref, model_out):
    """Return comparison dict with RMSE and per-stage errors."""
    stages = ["Healthy", "CKD1.5", "CKD3", "CKD4", "CKD5"]

    # Variables to validate: exclude Retics (Panel C detection uncertain)
    validated_vars = ["EPO", "Hb", "RBC"]
    # Retics is shown but excluded from RMSE (see REPLICATION_LOG.md)
    informative_vars = ["Retics"]

    comp = {}
    for var in validated_vars + informative_vars:
        if var not in ref:
            continue
        errors = []
        per_stage = {}
        for stage in stages:
            if stage not in ref.get(var, {}):
                continue
            ref_val   = ref[var][stage]
            model_val = model_out.get(stage, {}).get(var, None)
            if model_val is None:
                continue
            rel_err = abs(model_val - ref_val) / max(abs(ref_val), 1e-10)
            per_stage[stage] = {
                "ref": ref_val,
                "model": model_val,
                "rel_err": rel_err,
            }
            errors.append(rel_err)

        rmse_rel = float(np.sqrt(np.mean(np.array(errors) ** 2))) if errors else None
        comp[var] = {
            "rmse_relative": rmse_rel,
            "per_stage": per_stage,
            "validated": var in validated_vars,
        }

    # Overall RMSE across validated variables
    all_errs = []
    for var in validated_vars:
        if var in comp and comp[var]["rmse_relative"] is not None:
            all_errs.append(comp[var]["rmse_relative"])
    comp["_overall_rmse"] = float(np.mean(all_errs)) if all_errs else None
    return comp


# ---------------------------------------------------------------------------
# Determine PASS / INFORMATIVE_PASS / FAIL
# ---------------------------------------------------------------------------
def determine_status(comp):
    """
    PASS: all validated variables RMSE < 20%
    INFORMATIVE_PASS: overall RMSE < 35% (within expected range for model without
                      the supplementary parameter table)
    FAIL: overall RMSE >= 35%
    """
    overall = comp.get("_overall_rmse")
    if overall is None:
        return "FAIL"
    if overall < 0.20:
        return "PASS"
    elif overall < 0.35:
        return "INFORMATIVE_PASS"
    else:
        return "FAIL"


# ---------------------------------------------------------------------------
# Write JSON artifact (Rule 5)
# ---------------------------------------------------------------------------
def write_artifact(status, comp, model_out, csv_path):
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        git_hash = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=_THIS_DIR, text=True
        ).strip()
    except Exception:
        git_hash = "unknown"

    artifact = {
        "timestamp":      ts,
        "git_commit":     git_hash,
        "script":         os.path.basename(__file__),
        "paper_pmid":     "38125882",
        "figure":         "Fig3",
        "input_csv":      os.path.basename(csv_path),
        "status":         status,
        "overall_rmse_relative": comp.get("_overall_rmse"),
        "validated_variables": ["EPO", "Hb", "RBC"],
        "excluded_variables": ["Retics (Panel C digitization uncertain)"],
        "comparison":     comp,
        "model_outputs":  model_out,
    }

    out_path = os.path.join(EVIDENCE_DIR, f"M025_fig3_{ts}.json")
    with open(out_path, "w") as f:
        json.dump(artifact, f, indent=2)
    print(f"\nArtifact: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Plot (optional — only if matplotlib available)
# ---------------------------------------------------------------------------
def make_plot(ref, model_out, output_path):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("  matplotlib not available — skipping plot")
        return

    stages = ["Healthy", "CKD1.5", "CKD3", "CKD4", "CKD5"]
    stage_x = np.arange(len(stages))

    vars_panels = [
        ("EPO",    "EPO (IU/L)"),
        ("Hb",     "Hb (g/dL)"),
        ("Retics", "Retics (10^12/L)"),
        ("RBC",    "RBC (10^12/L)"),
    ]

    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    for ax, (var, label) in zip(axes, vars_panels):
        ref_vals   = [ref.get(var, {}).get(s, np.nan) for s in stages]
        model_vals = [model_out.get(s, {}).get(var, np.nan) for s in stages]

        ax.plot(stage_x, ref_vals,   "ro--", label="Ref VP (Fig 3)", ms=8)
        ax.plot(stage_x, model_vals, "bs-",  label="Model",         ms=6)
        ax.set_xticks(stage_x)
        ax.set_xticklabels(stages, rotation=20, ha="right")
        ax.set_ylabel(label)
        ax.legend(fontsize=7)
        ax.set_title(label)
        if var == "Retics":
            ax.set_title(f"{label}\n(uncertain digitization)")

    fig.suptitle("Roy 2023 Fig 3 — Model vs Reference VP", fontsize=11)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Plot: {output_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--spinup", type=float, default=30_000,
                        help="Spin-up time [h] for CKD steady state")
    parser.add_argument("--no-plot", action="store_true")
    args = parser.parse_args()

    print("=== Roy 2023 Fig 3 Replication ===")
    print(f"  CSV: {CSV_PATH}")

    # Load reference data
    print("\n1. Loading digitized reference VP values ...")
    ref = load_ref_csv(CSV_PATH)
    for var, stages_dict in ref.items():
        for stage, val in stages_dict.items():
            print(f"  {var} {stage}: {val:.4f}")

    # Run model
    print("\n2. Running model for each CKD stage ...")
    model_out = run_all_stages(spinup_h=args.spinup)

    # Compare
    print("\n3. Comparison (model vs digitized reference VP):")
    comp = compare(ref, model_out)
    for var, vinfo in comp.items():
        if var.startswith("_"):
            continue
        rmse = vinfo.get("rmse_relative")
        tag = "(validated)" if vinfo.get("validated") else "(informative)"
        if rmse is not None:
            print(f"  {var} RMSE={rmse*100:.1f}% {tag}")
        for stage, sinfo in vinfo.get("per_stage", {}).items():
            print(f"    {stage}: ref={sinfo['ref']:.3f}, "
                  f"model={sinfo['model']:.3f}, "
                  f"rel_err={sinfo['rel_err']*100:.1f}%")

    overall = comp.get("_overall_rmse")
    print(f"\n  Overall RMSE (EPO+Hb+RBC): {overall*100:.1f}%" if overall else "  No RMSE")

    # Status
    status = determine_status(comp)
    print(f"\n  STATUS: {status}")

    # Artifact
    artifact_path = write_artifact(status, comp, model_out, CSV_PATH)

    # Plot
    if not args.no_plot:
        plot_path = os.path.join(EVIDENCE_DIR, "M025_fig3_comparison.png")
        print("\n4. Generating comparison plot ...")
        make_plot(ref, model_out, plot_path)

    # Exit code
    if status == "FAIL":
        sys.exit(1)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
